name: Trigger an alpha release build
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "mk-actions-notify-server-trigger-packages-workflow"
    paths:
      - "deps/**"
      - ".github/workflows/**"

jobs:
  trigger_alpha_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger an alpha build in rabbitmq/server-packages
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.RABBITMQCI_BOT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/rabbitmq/server-packages/dispatches \
            -d '{"event_type": "new_4.1.x_alpha", "client_payload": {"prerelease": true, "prerelease_kind": "alpha", "prerelease_identifier": "${{ github.ref }}", "base_version": "4.1.0"}}'
