name: "Trigger a 4.1.x alpha release build"
on:
  workflow_dispatch:
  push:
    branches:
      # will become v4.1.x a few weeks before the release
      - "main"
    paths:
      - "deps/*/src/**"
      - 'deps/rabbitmq_management/priv/**'
      - ".github/workflows/**"
env:
  DEV_WORKFLOW_REPOSITORY: "rabbitmq/server-packages"
jobs:
  trigger_alpha_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a 4.1.x alpha release build in ${{ env.DEV_WORKFLOW_REPOSITORY }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.RABBITMQCI_BOT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.DEV_WORKFLOW_REPOSITORY }}/dispatches \
            -d '{ "event_type": "new_4.1.x_alpha", "client_payload": {"release_repository": "${{ env.DEV_WORKFLOW_REPOSITORY }}", "release_description": "Commit: https://github.com/rabbitmq/rabbitmq-server/commit/${{ github.sha }}, pushed at: ${{ github.event.repository.pushed_at }}", "prerelease": true, "prerelease_kind": "alpha", "prerelease_identifier": "${{ env.PRERELEASE_IDENTIFIER }}", "release_title": "RabbitMQ ${{ vars.SERVER_41_NEXT_PATCH_VERSION }}-alpha.${{ env.PRERELEASE_IDENTIFIER }} (${{ github.event.repository.pushed_at }})", "base_version": "${{ vars.SERVER_41_NEXT_PATCH_VERSION }}" }}'
